assets:
  crypto:
    - BTC-USD
  stocks:
    - ^IXIC  # NASDAQ Index
  forex:
    - EURUSD=X
    - GBPUSD=X
    - GBPJPY=X
    - USDJPY=X
    - USDCAD=X
    - AUDCAD=X

notification:
  discord:
    enabled: true
  logging:
    enabled: true
    level: INFO