# Configuration for Market Structure Monitor Service

# Assets to monitor, grouped by category
assets:
  crypto:  # Cryptocurrency assets
    - BTCUSDT  # Bitcoin vs USDT
  stocks:  # Stock indices
    - NQ  # NASDAQ Futures
  forex:  # Foreign exchange pairs
    - EURUSD=X  # Euro vs USD
    - GBPUSD=X  # British Pound vs USD

notification:
  discord:
    enabled: true  # Enable Discord notifications
  logging:
    enabled: true  # Enable logging
    level: INFO  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)

# Additional settings (optional)
settings:
  timezone: "America/New_York"  # Default timezone for timestamps
  interval_minutes: 15  # Monitoring interval in minutes